### ISSUE TITLE
OPNArp fails to start

### ISSUE THREAD

**Issue by StarkZarn** [mimugmail/opn-repo#149]
On the newest OPNSense release, OPNArp no longer starts.

- version:  23.1.5_4-amd64
- Error:
```
[09-Apr-2023 10:53:04 America/Los_Angeles] ArgumentCountError: Too few arguments to function OPNsense\Core\Api\ServiceController::startAction(), 0 passed and at least 1 expected in /usr/local/opnsense/mvc/app/controllers/OPNsense/Core/Api/ServiceController.php:74
Stack trace:
#0 [internal function]: OPNsense\Core\Api\ServiceController->startAction()
#1 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Core\Api\ServiceController), 'startAction', Array)
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#3 /usr/local/opnsense/www/api.php(24): Phalcon\Mvc\Application->handle('/api/core/servi...')
#4 {main}
```

**Comment by mimugmail** [comment]
Looks weird, I cant reproduce on my end, works fine here.
Can you reinstall the plugin?

**Comment by mimugmail** [comment]
But do you see anything in the logs?

**Comment by fernat** [comment]
I'm seeing the same issue, posted about it here:

https://forum.opnsense.org/index.php?topic=20827.135

The service appears to run and start fine from the opn-arp service pane in the GUI but the Dashboard services widget appears broken.

I dont see any errors in the logs. You asked if I saw any errors when starting the service from the command line. I can't figure out how to do that. Any guidance would be appreciated.

**Comment by fernat** [comment]
> Well, i may have spoke too soon... The service appears to be running now, which is great, but the dashboard widget on the homepage displays that it's stopped, and clicking the start button from there is what generates this error. So it's possible my issue here is improperly titled.

Did you get this resolved?

**Comment by mimugmail** [comment]
Should be fixed now in latest update

**Comment by fernat** [comment]
Awesome thanks, looks to have fixed the issue in that the damean shows green and started.

The service column is still missing a value and if I restart the service from the dashboard widget I'm still seeing a crash.
